#!/bin/bash
#SBATCH --job-name=brainlife_task
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --time=02:00:00
#SBATCH --account=your_account
#SBATCH --qos=normal
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=your_email@domain.com
#SBATCH --output=/scratch/brainlife/outputs/brainlife_%j.out
#SBATCH --error=/scratch/brainlife/errors/brainlife_%j.err
#SBATCH --chdir=/scratch/brainlife

# Brainlife Task Execution Script
# This script is automatically generated by pybrainlife for Slurm execution
# Task ID: ${BRAINLIFE_TASK_ID}
# App: ${BRAINLIFE_APP_NAME}

set -e

# Set up environment variables
export BRAINLIFE_TASK_ID=${SLURM_JOB_ID}
export BRAINLIFE_WORK_DIR=${SLURM_SUBMIT_DIR}
export BRAINLIFE_APP_NAME=${BRAINLIFE_APP_NAME:-brainlife_app}
export BRAINLIFE_PROJECT_ID=${BRAINLIFE_PROJECT_ID}
export BRAINLIFE_RESOURCE_ID=${BRAINLIFE_RESOURCE_ID}

# Create working directories
mkdir -p ${BRAINLIFE_WORK_DIR}/data
mkdir -p ${BRAINLIFE_WORK_DIR}/output
mkdir -p ${BRAINLIFE_WORK_DIR}/logs

# Log job information
echo "=========================================="
echo "Brainlife Slurm Job Information"
echo "=========================================="
echo "Job ID: ${SLURM_JOB_ID}"
echo "Task ID: ${BRAINLIFE_TASK_ID}"
echo "App Name: ${BRAINLIFE_APP_NAME}"
echo "Project ID: ${BRAINLIFE_PROJECT_ID}"
echo "Resource ID: ${BRAINLIFE_RESOURCE_ID}"
echo "Working Directory: ${BRAINLIFE_WORK_DIR}"
echo "Partition: ${SLURM_JOB_PARTITION}"
echo "Nodes: ${SLURM_JOB_NODELIST}"
echo "CPUs: ${SLURM_CPUS_PER_TASK}"
echo "Memory: ${SLURM_MEM_PER_CPU}"
echo "Time Limit: ${SLURM_TIME_LIMIT}"
echo "Start Time: $(date)"
echo "=========================================="

# Load required modules
echo "Loading modules..."
module load singularity
module load python/3.8
module load git

# Set up Python environment
echo "Setting up Python environment..."
export PYTHONPATH="${BRAINLIFE_WORK_DIR}/python:$PYTHONPATH"
export SINGULARITY_CACHEDIR="/scratch/singularity_cache"
export TMPDIR="/scratch/tmp"

# Create temporary directories
mkdir -p ${SINGULARITY_CACHEDIR}
mkdir -p ${TMPDIR}

# Download input data
echo "Downloading input data..."
cd ${BRAINLIFE_WORK_DIR}/data

# Example data download (replace with actual Brainlife data download logic)
# curl -H "Authorization: Bearer ${BRAINLIFE_TOKEN}" \
#      "https://brainlife.io/api/dataset/${BRAINLIFE_DATASET_ID}/download" \
#      -o input_data.tar.gz
# tar -xzf input_data.tar.gz

echo "Input data downloaded successfully"

# Download application container
echo "Downloading application container..."
cd ${BRAINLIFE_WORK_DIR}

# Example container download (replace with actual Brainlife container download logic)
# singularity pull --dir ${SINGULARITY_CACHEDIR} \
#                  docker://brainlife/${BRAINLIFE_APP_NAME}:latest

echo "Application container downloaded successfully"

# Run the application
echo "Running application..."
cd ${BRAINLIFE_WORK_DIR}

# Example application execution (replace with actual Brainlife app execution logic)
# singularity run --bind ${BRAINLIFE_WORK_DIR}/data:/input:ro \
#                 --bind ${BRAINLIFE_WORK_DIR}/output:/output \
#                 --bind ${BRAINLIFE_WORK_DIR}/logs:/logs \
#                 ${SINGULARITY_CACHEDIR}/${BRAINLIFE_APP_NAME}_latest.sif \
#                 --input /input \
#                 --output /output \
#                 --config ${BRAINLIFE_APP_CONFIG}

# For demonstration, create a simple output
echo "Application execution completed" > ${BRAINLIFE_WORK_DIR}/output/result.txt
echo "Processing time: $(date)" >> ${BRAINLIFE_WORK_DIR}/output/result.txt

echo "Application completed successfully"

# Upload results
echo "Uploading results..."
cd ${BRAINLIFE_WORK_DIR}/output

# Example result upload (replace with actual Brainlife result upload logic)
# tar -czf results.tar.gz *
# curl -H "Authorization: Bearer ${BRAINLIFE_TOKEN}" \
#      -F "file=@results.tar.gz" \
#      "https://brainlife.io/api/task/${BRAINLIFE_TASK_ID}/upload"

echo "Results uploaded successfully"

# Clean up temporary files
echo "Cleaning up temporary files..."
rm -rf ${BRAINLIFE_WORK_DIR}/data/*
rm -rf ${TMPDIR}/*

# Log completion
echo "=========================================="
echo "Brainlife Slurm Job Completed"
echo "=========================================="
echo "End Time: $(date)"
echo "Exit Code: 0"
echo "=========================================="

exit 0

